#!/usr/bin/env node

var { server } = require('./server.js');

server.on('listening', () => {
  console.log('Server listening for requests');
});

server.on('error', (err) => {
  console.error(`${err.name}: ${err.message}`);
});
